<?php

/**
 * Implementation of hook_entity_info_alter()
 */
function osu_widgets_entity_info_alter(&$entity_info) {

  // Carousel
  $entity_info['fieldable_panels_pane']['bundles']['osu_carousel'] = array(
    'label' => t('Add carousel'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_link.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/osu_carousel',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
