<?php
/**
 * @file
 * Code for the OSU Widgets feature.
 */

include_once 'osu_widgets.features.inc';

/**
 * Implementation of hook_entity_info_alter()
 */
function osu_widgets_entity_info_alter(&$entity_info) {

  // Carousel
  $entity_info['fieldable_panels_pane']['bundles']['osu_carousel'] = array(
    'label' => t('Add carousel'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_link.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/osu_carousel',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );

  // Slideshow
  $entity_info['fieldable_panels_pane']['bundles']['osu_slideshow'] = array(
    'label' => t('Add slideshow'),
    'pane category' => t('Custom'),
    'pane top level' => TRUE,
    'pane icon' => drupal_get_path('module', 'panopoly_widgets') . '/images/icon_link.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      'real path' => 'admin/structure/fieldable-panels-panes/manage/osu_slideshow',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_libraries_info().
 */
function osu_widgets_libraries_info() {
  $libraries['bxslider'] = array(
    'name' => 'bxSlider',
    'vendor url' => 'http://bxslider.com',
    'download url' => 'http://bxslider.com/lib/jquery.bxslider.zip',
    'version' => '4',
    'files' => array(
      'js' => array('jquery.bxslider.min.js'),
      'css' => array('jquery.bxslider.css'),
    ),
    'integration files' => array(
      'osu_widgets' => array(
        'js' => array('osu_widgets.js'),
        'css' => array('osu_widgets.css'),
      ),
    ),
  );

  return $libraries;
}

/**
 * Implements hook_ds_field_theme_functions_info().
 */
function osu_widgets_ds_field_theme_functions_info() {
  return array(
    'theme_ds_field_carousel' => t('Carousel'),
    'theme_ds_field_slideshow' => t('Slideshow'),
    'theme_ds_field_slideshow_image' => t('Slideshow Image'),
  );
}

function theme_ds_field_slideshow_image($variables) {

  $output = '';
  $output .= '<div class="slideshow-image-wrapper">';

  foreach ($variables['items'] as $delta => $item) {
    $output .= drupal_render($item);
  }

  $output .= '<div class="slideshow-image-bottom"></div>';
  $output .= '</div>';

  return $output;
}

function theme_ds_field_slideshow($variables) {

  libraries_load('bxslider');

  $output = '';
  $output .= '<ul class="bxslideshow">';

  foreach ($variables['items'] as $delta => $item) {
    $rendered_item = drupal_render($item);
    $output .= '<li>' . $rendered_item . '</li>';
  }

  $output .= '</ul>';

  return $output;
}

/**
 * Theme function to output the carousel.
 * This specifically themes a field collection with the fields
 * osu_carousel_link and osu_carousel_image.
 */
function theme_ds_field_carousel($variables) {

  libraries_load('bxslider');

  $output = '';
  $output .= '<ul class="bxcarousel">';

  // Render the items.
  foreach ($variables['items'] as $delta => $item) {
    $collection = reset($item['entity']['field_collection_item']);
    $image = $collection['field_osu_carousel_image'];
    $title = $collection['field_osu_carousel_title'];
    $rendered_image = drupal_render($image);
    $rendered_title = drupal_render($title);

    // set url if it exists
    $url = isset($collection['field_osu_carousel_link']) ?
      $collection['field_osu_carousel_link']['#items'][0]['url'] :
      FALSE;

    $image_and_title_output = $rendered_image . '<p>' . $rendered_title . '</p>';

    if($url) {
      $image_and_title_output = '<a href="' . $url . '">' . $image_and_title_output . '</a>';
    }

    $output .= '<li>' . $image_and_title_output . '</li>';
  }

  $output .= '</ul>';
  return $output;
}

